CREATE TABLE tickets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    ticket TEXT NOT NULL,

    user_id BIGINT NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NULL
);