version: "3.8"

services:
  db:
    image: mysql:8
    container_name: forum-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    build: .
    container_name: forum-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/forum_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT: MiPasswordUltraSegura123!@#QueCumpleConLaLongitud